import { ITask } from '@/shared/interfaces/task.interfaces';

export const data: ITask[] = [
	{
		id: 0,
		text: 'Сходить в столовую',
		category: 'social',
		deadline: new Date('2033-10-05'),
		reward_amount: 15,
		reward_type: 'coins',
		task_type: 'social',
		is_done: false,
	},
	{
		id: 1,
		text: 'Сходить в курилку',
		category: 'social',
		deadline: new Date('2033-10-05'),
		reward_amount: 15,
		reward_type: 'coins',
		task_type: 'social',
		is_done: false,
	},
	{
		id: 2,
		text: 'Выйграть хахатон',
		category: 'social',
		deadline: new Date('2033-10-05'),
		reward_amount: 15,
		reward_type: 'coins',
		task_type: 'social',
		is_done: false,
	},
	{
		id: 3,
		text: 'Шампунь жумайсынба',
		category: 'social',
		deadline: new Date('2003-10-05'),
		reward_amount: 15,
		reward_type: 'coins',
		task_type: 'social',
		is_done: false,
	},
	{
		id: 4,
		text: '10000 шагов за день',
		category: 'social',
		deadline: new Date('2033-10-05'),
		reward_amount: 15,
		reward_type: 'coins',
		task_type: 'social',
		is_done: true,
	},
	{
		id: 5,
		text: 'Помыться перед работой',
		category: 'social',
		deadline: new Date('2033-10-05'),
		reward_amount: 15,
		reward_type: 'coins',
		task_type: 'social',
		is_done: true,
	},
	{
		id: 6,
		text: 'Большой БУШИЗМ',
		category: 'social',
		deadline: new Date('2033-10-05'),
		reward_amount: 15,
		reward_type: 'coins',
		task_type: 'social',
		is_done: true,
	},
	{
		id: 7,
		text: 'далеко',
		category: 'social',
		deadline: new Date('2003-10-05'),
		reward_amount: 15,
		reward_type: 'coins',
		task_type: 'social',
		is_done: true,
	},
];
